from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

# Create your views here.
def home(request):
  return HttpResponse("<h1>Hello Django!</h1>")

def function_view(request):
    context = {
        'page_title': 'Function-Based View',
        'page_heading': 'Welcome to the Function-Based View',
        'page_content': 'This is the content generated by the function-based view.',
    }
    return render(request, 'bootswatch.html', context)



class ClassView(View):
  def get(self, request):
      context = {
          'page_title': 'Big Wave Surfing',
          'page_heading': 'Welcome to the 3rd most dangerous sport in the world',
          'page_content': 'This is Nazaré, Portugal, where giant waves are formed due to a submarine canyon called the "Nazaré Canyon".  It is the largest underwater canyon in Europe and is about 230 kilometers (140 miles) long with a depth of approximately 5,000 metres (16,000 ft).',
      }
      return render(request, 'bigwavesurfing.html', context)


